export {
  LABEL_EXTRACTION_SCHEMA_VERSION,
  GovernmentWarningSchemaV1,
  LabelExtractionSchemaV1,
  LabelExtractionSchema,
  parseLabelExtraction,
  LABEL_EXTRACTION_FIELD_DEFINITIONS,
  createEmptyExpectedLabel,
  getExpectedValueAtPath,
  hasIncompleteExpectedLabel,
  setExpectedValueAtPath,
  type LabelFieldDefinition,
  type ExpectedLabelValue,
  type ExpectedLabelValues,
  type GovernmentWarningV1,
  type LabelExtractionV1,
  type LabelExtraction,
  type LabelExtractionParseResult,
} from "./schemas/label/index.js";

export {
  type SchemaValidationIssues,
  type SupportedMediaType,
  type VerifyLabelBatchItemResult,
  type VerifyLabelBatchRequest,
  type VerifyLabelBatchResponse,
  type VerifyLabelErrorResponse,
  type VerifyLabelImageRequest,
  type VerifyLabelSuccessResponse,
} from "./api/verify-label.js";
